[package]
name = "easy_editor"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "crates/lcf-core",
    "crates/lcf-codegen",
]

[dependencies]
eframe = { version = "0.36.1", features = ["persistence"] }  # latest stable
egui = "0.36.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25.10"        # for loading chipsets
rfd = "0.17.2"          # native file picker
png = "0.18.1"
rust-i18n = "3"
sys-locale = "0.3"
rodio = "0.22"
lcf-core = { path = "crates/lcf-core" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Media_Multimedia", "Win32_Foundation"] }
